version: '3.7'
services:

  geolocation:
    image: "pds.stardust:5005/geolocation:latest-staging"
    ports:
      - "8081:8081"
    networks:
      - pds
    extra_hosts:
      - "node1:192.168.0.21"
      - "node2:192.168.0.22"
      - "node3:192.168.0.23"
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - spring_profiles_active=staging
    volumes:
      - /mnt/geolocation-config:/config
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

  sensor:
    image: "pds.stardust:5005/sensor:latest-staging"
    ports:
      - "8083:8083"
    networks:
      - pds
    extra_hosts:
      - "node1:192.168.0.21"
      - "node2:192.168.0.22"
      - "node3:192.168.0.23"
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - spring_profiles_active=staging
    volumes:
      - /mnt/sensor-config:/config
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

  account:
    image: "pds.stardust:5005/account:latest-staging"
    ports:
      - "8085:8085"
    networks:
      - pds
    extra_hosts:
      - "node1:192.168.0.21"
      - "node2:192.168.0.22"
      - "node3:192.168.0.23"
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - spring_profiles_active=staging
    volumes:
      - /mnt/account-config:/config
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

  frequentation:
    image: "pds.stardust:5005/frequentation:latest-staging"
    ports:
      - "8084:8084"
    networks:
      - pds
    extra_hosts:
      - "node1:192.168.0.21"
      - "node2:192.168.0.22"
      - "node3:192.168.0.23"
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - spring_profiles_active=staging
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

  kms:
    image: "pds.stardust:5005/kms:latest-staging"
    ports:
      - "8082:8082"
    networks:
      - pds
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - spring_profiles_active=staging
    volumes:
      - /mnt/kms-config:/config
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

  apigtw:
    image: "pds.stardust:5005/apigtw:latest-staging"
    ports:
      - "8080:8080"
    networks:
      - pds
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
    volumes:
      - /mnt/apigtw-config:/config
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 3

  cspath:
    image: "pds.stardust:5005/cspath:latest-staging"
    ports:
      - "3000:3000"
    networks:
      - pds
    volumes:
      - /mnt/cspath/ssl:/usr/src/app/ssl
    extra_hosts:
      - "node1:192.168.0.21"
      - "node2:192.168.0.22"
      - "node3:192.168.0.23"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  pds:

