version: '3.7'
services:

  geolocation:
    image: "pds.stardust:5005/geolocation:${VERSION}"
    ports:
      - "8081:8081"
    networks:
      - pds
    extra_hosts:
      - "node1:192.168.0.31"
      - "node2:192.168.0.32"
      - "node3:192.168.0.33"
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - spring_profiles_active=prod
    volumes:
      - /mnt/geolocation-config:/config
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

  sensor:
    image: "pds.stardust:5005/sensor:${VERSION}"
    ports:
      - "8083:8083"
    networks:
      - pds
    extra_hosts:
      - "node1:192.168.0.31"
      - "node2:192.168.0.32"
      - "node3:192.168.0.33"
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - spring_profiles_active=prod
    volumes:
      - /mnt/sensor-config:/config
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

  account:
    image: "pds.stardust:5005/account:${VERSION}"
    ports:
      - "8085:8085"
    networks:
      - pds
    extra_hosts:
      - "node1:192.168.0.31"
      - "node2:192.168.0.32"
      - "node3:192.168.0.33"
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - spring_profiles_active=prod
    volumes:
      - /mnt/account-config:/config
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

  frequentation:
    image: "pds.stardust:5005/frequentation:${VERSION}"
    ports:
      - "8084:8084"
    networks:
      - pds
    extra_hosts:
      - "node1:192.168.0.31"
      - "node2:192.168.0.32"
      - "node3:192.168.0.33"
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - spring_profiles_active=prod
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

  kms:
    image: "pds.stardust:5005/kms:${VERSION}"
    ports:
      - "8082:8082"
    networks:
      - pds
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - spring_profiles_active=prod
    volumes:
      - /mnt/kms-config:/config
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

  facialrecognition:
    image: "pds.stardust:5005/facialrecognition:${VERSION}"
    ports:
      - "5000:5000"
    networks:
      - pds
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3     

  apigtw:
    image: "pds.stardust:5005/apigtw:${VERSION}"
    ports:
      - "8080:8080"
    networks:
      - pds
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
    volumes:
      - /mnt/apigtw-config:/config
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 3

  cspath:
    image: "pds.stardust:5005/cspath:${VERSION}"
    ports:
      - "3000:3000"
    networks:
      - pds
    volumes:
      - /mnt/cspath/ssl:/usr/src/app/ssl
    extra_hosts:
      - "node1:192.168.0.31"
      - "node2:192.168.0.32"
      - "node3:192.168.0.33"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  pds:

